name: Continuous Development Pipeline

on: pull_request

jobs:
  build:
    name: Build

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          apt install python3.8 python3.8-venv

      - name: Build binary
        shell: bash -l {0}
        run: |
          make
          ./minesweeper -h
